[package]
name = "archivist"
version = "0.1.0"
authors = ["Andrew Chambers <ac@acha.ninja>"]
edition = "2018"

[dependencies]
getopts = "0.2"
failure = "0.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
cc = { version = "1.0"}
bindgen = "0.52.0"

