[package]
name = "bupstash"
version = "0.1.0"
authors = ["Andrew Chambers <ac@acha.ninja>"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
incremental = false

[dependencies]

crossbeam-channel = "0.4"
libc = "0.2"
rusqlite = { version = "0.23.1" }
getopts = "0.2"
failure = "0.1.6"
fs2 = "0.4.3"
codemap = "0.1.2"
codemap-diagnostic = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bare = { git = "https://git.sr.ht/~tdeo/serde_bare", rev = "2e330a7e37ca433c515d2a05128308fc98335300" }
pem = "0.8"
path-clean = "0.1.0"
parse_duration = "2.1.0"
tar = "0.4"
regex = "1"
glob = "0.3"
zstd = "0.5"
chrono = { version = "0.4", features = ["serde"]}
cfg-if = "0.1"
shlex = "0.1.1"
nix = "0.17.0"

[dev-dependencies]

tempfile = "3"

[build-dependencies]

pkg-config = "0.3"

