[package]
name = "archivist"
version = "0.1.0"
authors = ["Andrew Chambers <ac@acha.ninja>"]
edition = "2018"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
incremental = false

[dependencies]

crossbeam = "0.7"
libc = "0.2"
rusqlite = { version = "0.21.0", features = ["bundled"] }
getopts = "0.2"
failure = "0.1.6"
fs2 = "0.4.3"
rand = "0.7.2"
tempdir = "0.3.7"
codemap = "0.1.2"
codemap-diagnostic = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1"
regex = "1"
glob = "0.3"
zstd = "0.5"
futures = "0.1"
rusoto_core = "0.42.0"
rusoto_s3 = "0.42.0"

[build-dependencies]
cc = { version = "1.0"}
bindgen = "0.53"

